language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121
branches:
  only:
    - master
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libaio1 libaio-dev
script:
  - dotnet restore && 
    dotnet build ./src/MySql.LightServer.Tests/project.json -f netcoreapp1.0
  - dotnet test  ./src/MySql.LightServer.Tests -f netcoreapp1.0
after_success:
  - test $TRAVIS_PULL_REQUEST = false &&
    curl -H "Content-Type:application/json" -H "Authorization:Bearer $APPVEYOR_AUTH_KEY" -X POST -d '{"accountName":"carlosjdelgado","projectSlug":"mysql-lightserver","branch":"master"}' https://ci.appveyor.com/api/builds 
     